support docker in container

diff --git a/dockerbase b/dockerbase
--- a/dockerbase
+++ b/dockerbase
@@ -318,6 +318,55 @@ run_start(){
   fi
 }
 
+run_run(){
+  if [ ! -e $cidfile ]
+     then
+       echo "No cid found, creating a new container"
+       ports=`cat $config_file | $docker_path run --rm -i -a stdout -a stdin $image ruby -e \
+              "require 'yaml'; puts YAML.load(STDIN.readlines.join)['expose'].map{|p| '-p ' << p.to_s << ' '}.join"`
+
+       set_template_info
+       set_volumes
+
+       existing=`$docker_path ps -a | awk '{ print $1, $(NF) }' | egrep " $config$" | awk '{ print $1 }'`
+       if [ ! -z $existing ];
+       then
+         echo "Found an existing container by its name, recovering cidfile, please rerun"
+         echo $existing > $cidfile
+         exit 1
+       fi
+
+       $docker_path run $restart_policy "${env[@]}" \
+         -h "`hostname`-$user-$cidname" \
+         -e DOCKER_HOST_IP=$docker_ip --name $user-$cidname \
+         -t --cidfile $cidfile $ports \
+         -d $volumes $local_container/$user-$cidname bash
+
+       exit 0
+     else
+       cid=`cat $cidfile`
+
+       if [ -z $cid ]
+       then
+         echo "Detected empty cid file, deleting, please re-run"
+         rm $cidfile
+         exit 1
+       fi
+
+       found=`$docker_path ps -q -a --no-trunc | grep $cid`
+       if [ -z $found ]
+       then
+         echo "Invalid cid file, deleting, please re-run"
+         rm $cidfile
+         exit 1
+       fi
+
+       echo "cid found, ensuring container is started"
+       $docker_path start `cat $cidfile`
+       exit 0
+  fi
+}
+
 run_bootstrap(){
   get_ssh_pub_key
 
@@ -444,6 +493,11 @@ case "$command" in
 
   start)
       run_start
+      exit 0
+      ;;
+
+  run)
+      run_run
       exit 0
       ;;
 
