add one more service: tomcat8

diff --git a/dockerbase b/dockerbase
--- a/dockerbase
+++ b/dockerbase
@@ -172,13 +172,13 @@ install_docker() {
   mkdir -p $cidpath
 }
 
-#if [ ! -e $config_file ]
-#  then
-#    echo "Config file was not found, ensure $config_file exists"
-#    echo ""
-#    echo "Available configs ( `cd $ctns_path && ls -dm *.yml | tr -s '\n' ' ' | awk '{ gsub(/\.yml/, ""); print }'`)"
-#    exit 1
-#fi
+if [ ! -e $config_file ]
+  then
+    echo "Config file was not found, ensure $config_file exists"
+    echo ""
+    echo "Available configs ( `cd $ctns_path && ls -dm *.yml | tr -s '\n' ' ' | awk '{ gsub(/\.yml/, ""); print }'`)"
+    exit 1
+fi
 
 if [ "$opt" != "--skip-prereqs" ] ; then
   prereqs
